# Generated by Django 4.2.7 on 2024-03-11 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='building_no',
            new_name='place',
        ),
    ]
