# Generated by Django 4.2.7 on 2024-03-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_building_no_area_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='acc_no',
            field=models.IntegerField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='ifsc',
            field=models.CharField(default=2, max_length=12),
            preserve_default=False,
        ),
    ]
