# Generated by Django 4.2.7 on 2024-03-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_donation_acc_no_donation_ifsc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='acc_no',
            field=models.IntegerField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='donation',
            name='ifsc',
            field=models.CharField(default='', max_length=12),
        ),
    ]
