# Generated by Django 4.2.7 on 2024-03-22 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_user_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waste',
            name='Quantity',
        ),
    ]
